# Generated by Django 3.1.2 on 2020-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('subsType', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('posts', models.CharField(default='', max_length=1000)),
                ('followers', models.CharField(default='', max_length=1000)),
                ('followings', models.CharField(default='', max_length=1000)),
                ('jobTitle', models.CharField(max_length=100)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('profilePic', models.CharField(default='', max_length=300)),
                ('resume', models.CharField(default='', max_length=300)),
                ('portfolio', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
