# Generated by Django 3.1.2 on 2020-11-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('image', models.CharField(default='', max_length=300)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
