# Generated by Django 3.1.2 on 2020-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='', upload_to='post'),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='portfolio',
            field=models.FilePathField(default='', path='portfolio'),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='profilePic',
            field=models.ImageField(default='', upload_to='profilePic'),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='resume',
            field=models.FileField(default='', upload_to='resume'),
        ),
    ]
