# Generated by Django 3.1.2 on 2020-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20201108_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sender_jobTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
