# Generated by Django 3.1.2 on 2020-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_posts_sender_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sender_fname',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sender_jobTitle',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sender_lname',
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='portfolio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='profilePic',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='resume',
            field=models.CharField(default='', max_length=500),
        ),
    ]
